#!/bin/bash
## cecho
## version 0.0.1 - initial
##################################################
cecho() {
  . $( dirname ${0} )/sh2/${FUNCNAME}.sh
  cecho ${@}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
cecho
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 17 Jul 2019 21:02:22 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
